### PR TITLE
Oj was removed from sensu in version 0.13.0.

### PR DESCRIPTION
**Pull request by squaresurf**
This swaps out the Oj parser for the JSON parser.

Here is a link to relevant section for the sensu changelog: [CHANGELOG.md](https://github.com/sensu/sensu/blob/c81c50a54bb746cfc6be952e75ed5ffcda2ccfb1/CHANGELOG.md#other-1)

### CODE REVIEW

**Comment by squaresurf** [comment]
I just realized that this was already opened: https://github.com/lusis/sensu_influxdb_handler/pull/5

@lusis feel free to close this if you like the other approach better.

**Comment by squaresurf** [comment]
@lusis have you decided whether you want to use this PR or #5?

**Comment by trgr** [comment]
Would also like this PR to be accepted.
Just encountered this issue, and had to manualy patch.

**Comment by squaresurf** [comment]
@lusis any update on this? Should I just close this PR?

**Comment by squaresurf** [comment]
I'm closing this as the PR is stale. Feel free to merge if you'd like :smile:

**Pull request closed without merging**
